services:
  frontend:
    build:
      context: ./cliente
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./cliente:/app:cached
      - /app/node_modules
    command: npm run dev

  backend:
    build:
      context: ./servidor
      dockerfile: Dockerfile.dev
    ports:
      - "3000:4000"
    volumes:
      - ./servidor:/app:cached
      - /app/node_modules
    command: npx nodemon src/index.js
    depends_on:
      - mongo
      - postgres

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jornada
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  pg_data:
